plugins {
    alias(libs.plugins.android.application).apply(false)
    alias(libs.plugins.android.library).apply(false)
    alias(libs.plugins.sqldelight.library).apply(false)
    alias(libs.plugins.kotlin.android).apply(false)
    alias(libs.plugins.ksp.plugin).apply(false)
    alias(libs.plugins.googleplay.plugin).apply(false)
    alias(libs.plugins.crashlytics.plugin).apply(false)
    alias(libs.plugins.kotlin.multiplatform).apply(false)
    alias(libs.plugins.kotlin.cocoapods).apply(false)
    alias(libs.plugins.kotlin.apollo).apply(false)
    alias(libs.plugins.kotlin.serialization).apply(false)
    alias(libs.plugins.crashkios).apply(false)
    alias(libs.plugins.kotlin.parcelize).apply(false)
    alias(libs.plugins.android.download).apply(false)
    alias(libs.plugins.compose.compiler).apply(false)
}
